language: node_js

node_js:
  - "4"
  - "6"

sudo: false

cache:
  directories:
    - "node_modules"
    - ".eslintcache"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - ~/.yarn/bin/yarn global add npm@latest

install: ~/.yarn/bin/yarn

script: ~/.yarn/bin/yarn run test-ci
