environment:
  matrix:
    #- nodejs_version: "4"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - choco install yarn
  - refreshenv
  - node --version
  - yarn --version
  - yarn install

cache:
  - node_modules
  - .eslintcache

test_script:
  - yarn run build
  # Some snapshot tests don't currently work on Windows, so the tests are
  # commented out. Jest complains that obsolete snapshot files exist, so the
  # "-u" will just delete those snapshots when running in the AppVeyor run,
  # instead of failing the build. Note that this means that all snapshot tests
  # WILL ALWAYS PASS, as it updates the snapshots.
  - yarn run jest -- -u --color

# Don't actually build.
build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
